version: "3.1"

services:
  api:
    image: centos:latest
    command: |
              bash -c " curl https://raw.githubusercontent.com/senolerd/openstack-docker/master/keystone.sh -o /keystone_entrypoint.sh
                       chmod +x /keystone_entrypoint.sh
                       /keystone_entrypoint.sh
                       /bin/bash || exit 0"
    deploy:
      replicas: 3
#      placement:
#        constraints: [ node.labels.type == static ]
#    restart: always
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - openstack.env
    environment:
      - DOCKER_HOST=$DOCKER_HOST
    secrets:
      - source: credential_0
        target: credential_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: credential_1
        target: credential_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_0
        target: fernet_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_1
        target: fernet_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: 10.0.0.71.crt
        target: 10.0.0.71.crt
        uid: '163'
        gid: '163'
        mode: 0644

      - source: 10.0.0.71.key
        target: 10.0.0.71.key
        uid: '163'
        gid: '163'
        mode: 0600

  db:
    image: mariadb:10.3.15
#    restart: always
    ports:
      - 3306:3306
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
     - openstack.env

  adminer:
    image: adminer
#    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:alpine
#    restart: always

  rabbitmq:
    image: rabbitmq:3.7.17-rc.1-alpine
#    restart: always
    env_file:
     - openstack.env
#

# These are the initial fernet keys. Need to be saved as a docker secret with name as secret before starting the stack.
# Keystoe's api servers will mount them as their fernet keys.
#
# DOCKER SECRETS AND VALUES TO BE SAVED TO SWARMED DOCKER
# fernet_0: DcieLAHZcz_pfc8ngIXiDFSVn9R5Jb0DqivAhLVXZCk=
# fernet_1: hFZdwewAkARAr-Ey-9bwvLSN9MGEL_PUnaWVM4Cf6mE=
# crediendial_0: CLOnhFQOoDHfiPpiJkN3LWTmylhanixBs__8HLRe92Q=
# crediendial_1: 0kkN87jywQlDlwMS0ySRIzB752OFmSlhz6QyxvO_l78=
#
# echo 'asdfad' | docker secret create credential_0 -
#
# (the dash end of the command is included to command)


secrets:
  credential_0:
    external: true
  credential_1:
    external: true
  fernet_0:
    external: true
  fernet_1:
    external: true
  10.0.0.71.crt:
    external: true
  10.0.0.71.key:
    external: true
