version: "3"
services:

  db:
    image: mariadb:10.3.15
    restart: always
    ports:
      - 3306:3306
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
     - openstack.env
    deploy:
      placement:
        constraints: [ node.labels.type == static ] # Dedicated placement 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints: [ node.labels.type == static ]

  memcached:
    image: memcached:alpine
    restart: always
    deploy:
      placement:
        constraints: [ node.labels.type == static ] 

  rabbitmq:
    image: rabbitmq:3.7.17-rc.1-alpine
    restart: always
    env_file:
     - openstack.env
    deploy:
      placement:
        constraints: [ node.labels.type == static ] 

  api:
    image: keystone:api
    restart: always
    ports:
      - 5000:5000
      - 35357:35357
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
     - openstack.env
    deploy:
      placement:
        constraints: [ node.labels.type == static ] 

