version: "3.6"

networks:
  default:
    external: true
    name: "$OVERLAY_NET_NAME"

services:
  keystone-api:
    image: centos:latest
    command: |
              bash -c "# keystone-api
                       curl https://raw.githubusercontent.com/senolerd/openstack-docker/master/branches/$OS_VERSION/etc/keystone.sh -o /keystone_entrypoint.sh
                       chmod +x /keystone_entrypoint.sh
                       /keystone_entrypoint.sh
                       /bin/bash || exit 0"
    deploy:
      replicas: 1
#      placement:
#        constraints: [ node.labels.type == static ]
#    restart: always
    ports:
      - "${KEYSTONE_PUBLIC_ENDPOINT_PORT}:${KEYSTONE_PUBLIC_ENDPOINT_PORT}"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - "${base}/openstack.env"
    environment:
      - DOCKER_HOST_ADDR=$DOCKER_HOST_ADDR
    secrets:
      - source: credential_0
        target: credential_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: credential_1
        target: credential_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_0
        target: fernet_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_1
        target: fernet_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: server.crt
        target: server.crt
        uid: '163'
        gid: '163'
        mode: 0644

      - source: server.key
        target: server.key
        uid: '163'
        gid: '163'
        mode: 0600

  keystone-db:
    image: mariadb:10.3.15
    ports:
     - "$MYSQL_PORT:$MYSQL_PORT"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - "${base}/openstack.env"

  keystone-adminer:
    image: adminer
    ports:
      - "$KEYSTONE_ADMINER_PORT:$KEYSTONE_ADMINER_PORT"

  keystone-memcached:
    image: memcached:alpine

  keystone-rabbitmq:
    image: rabbitmq:3.7.17-rc.1-alpine
    env_file:
     - "${base}/openstack.env"

secrets:
  credential_0:
    file: "$base/branches/$OS_VERSION/etc/credential_0"
  credential_1:
    file: "$base/branches/$OS_VERSION/etc/credential_1"
  fernet_0:
    file: "$base/branches/$OS_VERSION/etc/fernet_0"
  fernet_1:
    file: "$base/branches/$OS_VERSION/etc/fernet_1"
  server.key:
    file: "$base/branches/$OS_VERSION/etc/server.key"
  server.crt:
    file: "$base/branches/$OS_VERSION/etc/server.crt"
