version: "3.6"

networks:
  default:
    external: true
    name: ${OVERLAY_NET_NAME}

# networks:
#   default:
#     name: ${OVERLAY_NET_NAME}


services:
  keystone-api:
    image: ${KEYSTONE_DOCKER_IMAGE}
    command: |
              bash -c "# keystone-api
                       curl https://raw.githubusercontent.com/senolerd/openstack-docker/master/branches/$OS_VERSION/etc/keystone.sh -o /keystone_entrypoint.sh
                       chmod +x /keystone_entrypoint.sh
                       /keystone_entrypoint.sh
                       httpd -DFOREGROUND
                       sleep 111d
                       /bin/bash || exit 0"
    deploy:
      replicas: 1
#      placement:
#        constraints: [ node.labels.type == static ]
#    restart: always
    ports:
      - ${KEYSTONE_PUBLIC_ENDPOINT_PORT}:${KEYSTONE_PUBLIC_ENDPOINT_PORT}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ${base}/openstack.env
    environment:
      - DOCKER_HOST_ADDR=${DOCKER_HOST_ADDR}
    secrets:
      - source: credential_0
        target: credential_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: credential_1
        target: credential_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_0
        target: fernet_0
        uid: '163'
        gid: '163'
        mode: 0600

      - source: fernet_1
        target: fernet_1
        uid: '163'
        gid: '163'
        mode: 0600

      - source: server_key.pem
        target: server_key.pem
        uid: '163'
        gid: '163'
        mode: 0400

      - source: server_crt.pem
        target: server_crt.pem
        uid: '163'
        gid: '163'
        mode: 0644

      - source: ca_chain.pem
        target: ca_chain.pem
        uid: '163'
        gid: '163'
        mode: 0644


  keystone-db:
    image: ${MYSQL_DOCKER_IMAGE}
    ports:
     - ${MYSQL_PORT}:${MYSQL_PORT}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ${base}/openstack.env

  keystone-adminer:
    image: adminer
    ports:
      - ${KEYSTONE_ADMINER_PORT}:${KEYSTONE_ADMINER_PORT}

  keystone-memcached:
    image: ${MEMCACHED_DOCKER_IMAGE}

  keystone-rabbitmq:
    image: ${RABBITMQ_DOCKER_IMAGE}
    env_file:
     - ${base}/openstack.env

secrets:
  credential_0:
    file: ${base}/branches/$OS_VERSION/etc/credential_0
  credential_1:
    file: ${base}/branches/$OS_VERSION/etc/credential_1
  fernet_0:
    file: ${base}/branches/$OS_VERSION/etc/fernet_0
  fernet_1:
    file: ${base}/branches/$OS_VERSION/etc/fernet_1
  server_key.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/private/$target_host.key.pem
  server_crt.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/certs/$target_host.cert.pem
  ca_chain.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/certs/ca-chain.cert.pem
