version: "3.6"

networks:
  default:
    external: true
    name: ${OVERLAY_NET_NAME}

services:
  glance-api:
    image: ${GLANCE_DOCKER_IMAGE}
    command: |
              bash -c "# glance-api
                        curl https://raw.githubusercontent.com/senolerd/openstack-docker/master/branches/$OS_VERSION/etc/glance.sh -o /glance_entrypoint.sh
                        chmod +x /glance_entrypoint.sh
                        /glance_entrypoint.sh
                        /bin/bash || exit 0"
    deploy:
      replicas: 1
    ports:
      - ${GLANCE_PUBLIC_ENDPOINT_PORT}:${GLANCE_PUBLIC_ENDPOINT_PORT}
    dns:
      - 8.8.8.8
    env_file:
      - ${base}/openstack.env
    environment:
      - DOCKER_HOST_ADDR=${DOCKER_HOST_ADDR}
