version: "3.6"

networks:
  default:
    external: true
    name: ${OVERLAY_NET_NAME}

services:
  glance-api:
    image: ${GLANCE_DOCKER_IMAGE}
    command: |
              bash -c "# glance-api
                        curl https://raw.githubusercontent.com/senolerd/openstack-docker/master/branches/$OS_VERSION/etc/glance.sh -o /glance_entrypoint.sh
                        chmod +x /glance_entrypoint.sh
                        /glance_entrypoint.sh
                        /bin/bash || exit 0"
    deploy:
      replicas: 1
    ports:
      - ${GLANCE_PUBLIC_ENDPOINT_PORT}:${GLANCE_PUBLIC_ENDPOINT_PORT}
    dns:
      - 8.8.8.8
    env_file:
      - ${base}/openstack.env
    secrets:
      - source: ca_chain.pem
        target: "/etc/glance/ca_chain.pem"
        uid: '161'
        gid: '161'
        mode: 0644

      - source: server_key.pem
        target: /etc/glance/tls/server_key.pem
        uid: '161'
        gid: '161'
        mode: 0400

      - source: server_crt.pem
        target: /etc/glance/tls/server_crt.pem
        uid: '161'
        gid: '161'
        mode: 0644

    environment:
      - DOCKER_HOST_ADDR=${DOCKER_HOST_ADDR}

secrets:
  ca_chain.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/certs/ca-chain.cert.pem
  server_key.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/private/$target_host.key.pem
  server_crt.pem:
    file: ${base}/branches/${OS_VERSION}/etc/ca/intermediate/certs/$target_host.cert.pem


